version: "3.9"
services:
  angular:
    build: ./task-frontend-angular
    ports:
      - "4200:80"
    links:
      - backend
  backend:
    build: ./MongoExample
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_HTTP_PORT=https://+:5001
      - ASPNETCORE_URLS=http://+:5000
